// ===== TRUSTED HOSTS (global trusted + megathread list) =====

const BASE_TRUSTED_HOSTS = new Set([
  // Everyday global trusted sites (general)
  "google.com",
  "www.google.com",
  "gmail.com",
  "www.gmail.com",
  "youtube.com",
  "www.youtube.com",
  "reddit.com",
  "www.reddit.com",
  "github.com",
  "www.github.com",
  "sanjeeth-prakash.github.io",   // <--- your PiraTrue site
  "github.io",                    // optional, for any other github.io pages
  "gitlab.com",
  "www.gitlab.com",
  "linkedin.com",
  "www.linkedin.com",
  "instagram.com",
  "www.instagram.com",
  "twitter.com",
  "www.twitter.com",
  "x.com",
  "www.x.com",
  "facebook.com",
  "www.facebook.com",
  "discord.com",
  "www.discord.com",
  "stackoverflow.com",
  "www.stackoverflow.com",
  "cloudflare.com",
  "www.cloudflare.com",

  // Messaging & communication
  "whatsapp.com",
  "www.whatsapp.com",
  "web.whatsapp.com",
  "telegram.org",
  "web.telegram.org",
  "t.me",
  "signal.org",
  "web.skype.com",
  "skype.com",
  "zoom.us",
  "meet.google.com",

  // AI tools & LLM sites
  "openai.com",
  "chat.openai.com",
  "platform.openai.com",
  "claude.ai",
  "perplexity.ai",
  "gemini.google.com",
  "bard.google.com",
  "copilot.microsoft.com",
  "huggingface.co",
  "poe.com",
  "character.ai",
  "cursor.sh",
  "replit.com",
  "notion.so",

  // Dev & infra tools
  "developer.chrome.com",
  "superuser.com",
  "serverfault.com",
  "npmjs.com",
  "pypi.org",
  "python.org",
  "nodejs.org",
  "docker.com",
  "hub.docker.com",
  "ubuntu.com",
  "debian.org",

  // Megathread trusted piracy-related sites (your big list)
  "123anime.info",
  "1337x-status.org",
  "1337x.to",
  "18kami.com",
  "1fichier.com",
  "1movies.bz",
  "2024.myfreemp3juices.cc",
  "321movies.co.uk",
  "321movies.xyz",
  "3ost.ru",
  "456movie.nl",
  "abandonwaregames.net",
  "abflix.app",
  "abflix.xyz",
  "abyss.to",
  "academictorrents.com",
  "acermovies.fun",
  "aedownload.com",
  "aether.mom",
  "all-wish.me",
  "anichart.net",
  "anidap.se",
  "anidb.net",
  "anigo.to",
  "anihq.org",
  "anikuro.to",
  "anilist.co",
  "anime-skip.com",
  "animehub.ac",
  "animekai.pw",
  "animenana.com",
  "animenosub.to",
  "animepahe.pw",
  "animethemes.moe",
  "animetosho.org",
  "animexin.vip",
  "anitousen.com",
  "anizone.to",
  "ankergames.net",
  "annas-archive.gd",
  "annas-archive.gl",
  "annas-archive.pk",
  "appaudiobooks.com",
  "appdoze.net",
  "appnetica.com",
  "appstorrent.ru",
  "archive.org",
  "aria2.github.io",
  "artistgrid.cx",
  "ascendara.app",
  "asiaflix.cfd",
  "asiaflix.in",
  "asiaflix.live",
  "asiaflix.net",
  "astral-games.xyz",
  "audioaz.com",
  "audiobookbay.lu",
  "audiobooks4soul.com",
  "audioz.download",
  "autobrr.com",
  "azmp3.cc",
  "beatrice-raws.org",
  "beech.watch",
  "bigaudiobooks.com",
  "bingeflix.tv",
  "bitport.io",
  "bitsearch.to",
  "blaze.vercel.app",
  "bookaudiobooks.com",
  "brocoflix.xyz",
  "bt4gprx.com",
  "btdig.com",
  "buzzheavier.com",
  "byxatab.com",
  "canna-power.to",
  "catbox.moe",
  "chauthanh.info",
  "cinebolt.net",
  "cinema.bz",
  "cinemaos-v2.vercel.app",
  "cinezo.net",
  "cloudtorrents.com",
  "cnvmp3.com",
  "cobalt.tools",
  "codec.kyiv.ua",
  "coderprog.com",
  "collectionchamber.blogspot.com",
  "comix.to",
  "cornclick.com",
  "coursesbag.com",
  "cracked-games.org",
  "cracksurl.com",
  "cs.rin.ru",
  "cse.google.com",
  "dab.yeet.su",
  "dabmusic.xyz",
  "dailyuploads.net",
  "dashflix.top",
  "deezmate.com",
  "developify.ca",
  "diakov.net",
  "discord.gg",
  "doc.yaronzz.com",
  "docs.undi.rest",
  "dodi-repacks.download",
  "dodi-repacks.site",
  "donkey.to",
  "doodstream.com",
  "doubledouble.top",
  "download-soundtracks.com",
  "downloadfreecourse.com",
  "downloadmusicschool.com",
  "downloads.khinsider.com",
  "downloadsound.cloud",
  "downmagaz.net",
  "dramaday.me",
  "drop.lol",
  "ds4-windows.com",
  "easyupload.io",
  "ebook-hunter.org",
  "einthusan.tv",
  "elamigos.site",
  "elenemigos.com",
  "eltorr.com",
  "emby.media",
  "en2.freemp3.tube",
  "episodecalendar.com",
  "erickutcher.github.io",
  "es-de.org",
  "ext.to",
  "eztvstatus.org",
  "eztvx.to",
  "f-tv.watch",
  "fanfox.net",
  "faststream.online",
  "fastupload.io",
  "fearlessrevolution.com",
  "file.love",
  "file.pizza",
  "filecxx.com",
  "fileditch.com",
  "filemood.com",
  "filemoon.sx",
  "filepursuit.com",
  "files.rg-adguard.net",
  "filetransfer.kpn.com",
  "filmex.to",
  "fitgirl-repacks.site",
  "flexget.com",
  "flickermini.pages.dev",
  "flickystream.ru",
  "flingtrainer.com",
  "flix.smashystream.xyz",
  "flixer.su",
  "flixzone.co",
  "fluxyrepacks.xyz",
  "fondfont.com",
  "fontmeme.com",
  "fonts.google.com",
  "fontshub.pro",
  "forcoder.net",
  "forum.dirtywarez.com",
  "free-movies.to",
  "freecoursesite.com",
  "freedl.ink",
  "freeeducationweb.com",
  "freegogpcgames.com",
  "freemagazines.top",
  "freetubeapp.io",
  "freevideoeffect.com",
  "fsharetv.co",
  "fuckingfast.co",
  "fulllengthaudiobooks.net",
  "g-meh.com",
  "g4u.to",
  "galaxyaudiobook.com",
  "gamdie.com",
  "game-siphon.vercel.app",
  "gamebanana.com",
  "gamebounty.world",
  "gamecopyworld.com",
  "gamepcfull.com",
  "games4u.org",
  "gamesdrive.net",
  "gamesfrog.com",
  "gamespack.net",
  "gamevau.lt",
  "gamezdl.cc",
  "gen.paramore.su",
  "getcomics.org",
  "getfreegames.net",
  "getmusicbee.com",
  "getsurge.io",
  "gift4designer.net",
  "gload.to",
  "gofile.io",
  "gog-games.to",
  "goldenaudiobook.com",
  "gopeed.com",
  "greasyfork.org",
  "hakuneko.download",
  "hayase.watch",
  "hdaudiobooks.com",
  "hdvinnie.github.io",
  "heartive.pages.dev",
  "heroicgameslauncher.com",
  "hexload.com",
  "hi10anime.com",
  "hidan.sh",
  "hiddenpalace.org",
  "hotaudiobooks.com",
  "howlongtobeat.com",
  "hunterae.com",
  "hydrahd.info",
  "hydrahd.io",
  "icefy.top",
  "idope.se",
  "ifonts.xyz",
  "iina.io",
  "insmac.org",
  "installgames.net",
  "instances.cobalt.best",
  "intro-hd.net",
  "invidious.io",
  "iogames.space",
  "isthereanydeal.com",
  "ivigo.cc",
  "jdownloader.org",
  "jellyfin.org",
  "joytokey.net",
  "justbeamit.com",
  "kagane.org",
  "kaoskrew.org",
  "kayoanime.com",
  "kdramaost.com",
  "kisskh.co",
  "kissvk.pro",
  "kitsu.io",
  "knaben.eu",
  "kodi.tv",
  "kojima48.blogspot.com",
  "krakenfiles.com",
  "kupdf.net",
  "kuroiru.co",
  "kurozora.app",
  "kuudere.lol",
  "kuudere.to",
  "landrop.app",
  "lardbit.github.io",
  "lemmy.dbzer0.com",
  "letterboxd.com",
  "liber3.eth.limo",
  "libgen.li",
  "librarygenesis.net",
  "librivox.org",
  "lidarr.audio",
  "lightdl.xyz",
  "lightning-share.vercel.app",
  "litterbox.catbox.moe",
  "localsend.org",
  "lookmovie2.to",
  "lordflix.org",
  "lrepacks.net",
  "lucida.to",
  "m-zone.org",
  "m4ckd0ge-repacks.site",
  "macintoshgarden.org",
  "macx.ws",
  "madnessbeat.club",
  "mangabot.github.io",
  "mangabuddy.com",
  "mangadex.org",
  "mangafire.to",
  "mangahub.io",
  "mangakakalot.gg",
  "mangakatana.com",
  "mangapark.io",
  "mangapark.net",
  "mangapill.com",
  "manybooks.net",
  "mapple.tv",
  "massgrave.dev",
  "materialio.us",
  "meawfy.com",
  "media.cm",
  "mediafire.com",
  "mega.io",
  "megagames.com",
  "megaup.net",
  "mikudb.moe",
  "mirrorace.com",
  "mixdrop.ag",
  "mkvdrama.org",
  "moddingway.com",
  "monkrus.dvuzu.com",
  "monochrome.tf",
  "moontv.to",
  "motka.net",
  "movish.net",
  "mp3mango.net",
  "mp3vanced.online",
  "mpv.io",
  "mrantifun.net",
  "msearch.vercel.app",
  "muffon.netlify.app",
  "multiup.io",
  "musicdex.org",
  "musopen.org",
  "my-subs.co",
  "myanime.live",
  "myanimelist.net",
  "nepu.to",
  "new.space",
  "next-episode.net",
  "nicotine-plus.org",
  "nnmclub.to",
  "novelbuddy.com",
  "nyaa.land",
  "nyaa.si",
  "oceanofpdf.com",
  "oldgamesdownload.com",
  "oleksis.github.io",
  "oneforalldownloader.com",
  "onionshare.org",
  "online-courses.club",
  "online-fix.me",
  "opencritic.com",
  "openlibrary.org",
  "openvideofs.github.io",
  "oshi.at",
  "osmc.tv",
  "pahe.ink",
  "partner.steamgames.com",
  "pdfmagazines.club",
  "pdfroom.com",
  "peazip.github.io",
  "persepolisdm.github.io",
  "piped.kavin.rocks",
  "piped.video",
  "pivigames.blog",
  "pixeldrain-bypass.cybar.xyz",
  "pixeldrain.com",
  "playnite.link",
  "playseek.app",
  "playtorrio.pages.dev",
  "plc4me.com",
  "plugins4free.com",
  "plugintorrent.com",
  "pluto.tv",
  "poki.com",
  "polyuploader.vercel.app",
  "popcornmovies.org",
  "popr.ink",
  "posilej.cz",
  "potplayer.daum.net",
  "powder.media",
  "powvideo.net",
  "predb.me",
  "predb.net",
  "prowlarr.com",
  "proxymirrorlookmovie.github.io",
  "psa.wf",
  "pyload.net",
  "pymedusa.com",
  "radarr.video",
  "ramenflix.com",
  "rarefilmm.com",
  "ravebooksearch.com",
  "ravegamesearch.pages.dev",
  "ravesoftwaresearch.pages.dev",
  "rdrop.link",
  "readcomiconline.li",
  "recherche-ebook.fr",
  "redditblog.com",
  "redditinc.com",
  "releases.moe",
  "reloadedsteam.com",
  "renovatiorecords.blogspot.com",
  "rentry.co",
  "rentry.org",
  "repack-games.com",
  "repacklab.com",
  "rexagames.com",
  "rezi.one",
  "rivestream.xyz",
  "rootz.so",
  "rustorka.com",
  "rutor.info",
  "rutor.is",
  "rutracker.org",
  "saladroom.net",
  "sastatus.com",
  "scanlibs.com",
  "scene-rls.net",
  "schizoduckie.github.io",
  "sci-hub.ru",
  "sci-hub.se",
  "sci-hub.st",
  "scloud.ws",
  "scnlog.me",
  "screenopps.com",
  "seanime.rahim.app",
  "search.extto.com",
  "send.cm",
  "send.hrzn.cool",
  "send.vis.ee",
  "sendfa.st",
  "sendfilesencrypted.com",
  "sendvid.com",
  "sflix.fi",
  "shailendramaurya.github.io",
  "share.acgnx.se",
  "sickchill.github.io",
  "simkl.com",
  "smashystream.xyz",
  "soft98.ir",
  "softarchive.is",
  "sonarr.tv",
  "soundcloudmp3.cc",
  "spacedrop.app",
  "special-k.info",
  "spicetify.app",
  "spotdl.readthedocs.io",
  "spotidownloader.com",
  "spotifymate.com",
  "spotube.krtirtho.dev",
  "sprend.com",
  "squid.wtf",
  "stacher.io",
  "standardebooks.org",
  "steam-cracked.com",
  "steamdb.info",
  "steamgg.net",
  "steamora.net",
  "steamrip.com",
  "steamunderground.net",
  "stefnotch.github.io",
  "stream.telev.tv",
  "streamable.com",
  "streamtape.com",
  "streamtape.to",
  "subdl.com",
  "subhd.tv",
  "subsource.net",
  "subsplease.org",
  "substital.com",
  "sukidesuost.info",
  "support.reddithelp.com",
  "taiga.moe",
  "tapochek.net",
  "the-dark-games.com",
  "theindex.moe",
  "thetvapp.to",
  "theunarchiver.com",
  "thewiki.moe",
  "thirteenag.github.io",
  "tixati.com",
  "toffeeshare.com",
  "tokybook.com",
  "toonily.com",
  "torbox.app",
  "torrent-games.games",
  "torrent-games.net",
  "torrentquest.com",
  "torrminatorr.com",
  "trace.moe",
  "trakt.tv",
  "transmissionbt.com",
  "triahgames.com",
  "tube.cadence.moe",
  "tubitv.com",
  "undergroundgames.net",
  "union-crax.xyz",
  "uniquestream.net",
  "unpackerr.zip",
  "uploadnow.io",
  "upstream.to",
  "v1.gostreameast.link",
  "vegamovies.ms",
  "vgmdb.net",
  "videy.co",
  "vidnaija.com.ng",
  "vidoza.net",
  "vidplay.top",
  "vikingfile.com",
  "virgil-search.pages.dev",
  "virgil.samidy.com",
  "voe.sx",
  "warezforums.com",
  "watch.spencerdevs.xyz",
  "watch.streamflix.one",
  "wcofun.org",
  "web.ligaudio.ru",
  "webdrop.space",
  "webextension.org",
  "webmshare.com",
  "webtor.io",
  "webtorrent.io",
  "webwormhole.io",
  "weebcentral.com",
  "welib.org",
  "whereyouwatch.com",
  "win7games.com",
  "wiztorrent.com",
  "worldofpcgames.com",
  "worldscinema.org",
  "wormhole.app",
  "wotaku.wiki",
  "ww3.dramanice.video",
  "www.1shows.org",
  "www.7-zip.org",
  "www.addic7ed.com",
  "www.addictinggames.com",
  "www.aimp.ru",
  "www.anime-planet.com",
  "www.animefillerlist.com",
  "www.animeout.xyz",
  "www.animeparadise.moe",
  "www.animerealms.org",
  "www.arkadium.com",
  "www.backloggd.com",
  "www.bazarr.media",
  "www.bestmp3converter.com",
  "www.biglybt.com",
  "www.bingeclock.com",
  "www.cg-gamespc.com",
  "www.cineby.app",
  "www.cineby.sc",
  "www.coolmathgames.com",
  "www.crazygames.com",
  "www.cufonfonts.com",
  "www.dafontfree.io",
  "www.deluge-torrent.org",
  "www.dfonts.org",
  "www.digitalbook.io",
  "www.discografiascompletas.cc",
  "www.downloadpirate.com",
  "www.downthemall.org",
  "www.elmedia-video-player.com",
  "www.emudeck.com",
  "www.erai-raws.info",
  "www.file.io",
  "www.fontbolt.com",
  "www.fontget.com",
  "www.fonts4free.net",
  "www.fontspace.com",
  "www.fontsquirrel.com",
  "www.foobar2000.org",
  "www.freechinesefont.com",
  "www.freeclassicaudiobooks.com",
  "www.freedownloadmanager.org",
  "www.freegamesmax.com",
  "www.freejapanesefont.com",
  "www.freekoreanfont.com",
  "www.gamepassport.net",
  "www.gamingalexandria.com",
  "www.gog.com",
  "www.guru3d.com",
  "www.gutenberg.org",
  "www.jpopsingles.eu",
  "www.jumbomail.me",
  "www.justwatch.com",
  "www.keka.io",
  "www.kmplayer.com",
  "www.launchbox-app.com",
  "www.limetorrents.lol",
  "www.livechart.me",
  "www.locoloader.com",
  "www.macappdownload.com",
  "www.macbed.com",
  "www.magesy.blog",
  "www.mangaread.org",
  "www.metacritic.com",
  "www.mirrored.to",
  "www.miruro.tv",
  "www.moddb.com",
  "www.motrix.app",
  "www.msi.com",
  "www.myabandonware.com",
  "www.myanonamouse.net",
  "www.nexusmods.com",
  "www.noobsubs.com",
  "www.old-games.ru",
  "www.opensubtitles.com",
  "www.opensubtitles.org",
  "www.ovagames.com",
  "www.pcgamingwiki.com",
  "www.pikatorrent.com",
  "www.plex.tv",
  "www.plustransfer.com",
  "www.podnapisi.net",
  "www.potiongang.fr",
  "www.pressplay.top",
  "www.protondb.com",
  "www.qbittorrent.org",
  "www.redditinc.com",
  "www.retroarch.com",
  "www.seedr.cc",
  "www.senpai.moe",
  "www.sharrr.com",
  "www.sittingonclouds.net",
  "www.slsknet.org",
  "www.smplayer.info",
  "www.softlay.com",
  "www.squid-board.org",
  "www.squidify.org",
  "www.stevvgame.com",
  "www.storynory.com",
  "www.stremio.com",
  "www.subtitlecat.com",
  "www.systemrequirementslab.com",
  "www.teamos.xyz",
  "www.tokyoinsider.com",
  "www.tokyotosho.info",
  "www.torrentdownload.info",
  "www.torrentdownloads.pro",
  "www.torrentleech.org",
  "www.torrentmac.net",
  "www.torrentsafe.com",
  "www.transfernow.net",
  "www.tvsubs.net",
  "www.un4seen.com",
  "www.universalmediaserver.com",
  "www.up-4ever.net",
  "www.urbandictionary.com",
  "www.urlvoid.com",
  "www.vfxmed.com",
  "www.videolan.org",
  "www.vidyard.com",
  "www.warezbook.org",
  "www.wco.tv",
  "www.welib.st",
  "www.wemod.com",
  "www.whatismymovie.com",
  "www.win-rar.com",
  "www.wsgf.org",
  "www.xrel.to",
  "www.yasir252.com",
  "www.yout-ube.com",
  "www.zipware.org",
  "xprime.su",
  "xprime.tv",
  "xpwatch-v2.pages.dev",
  "xtremedownloadmanager.com",
  "y0urd34th.github.io",
  "yenime.net",
  "yesmovies.ag",
  "yflix.to",
  "yoyomovies.net",
  "ytdn.netlify.app",
  "ytiz.xyz",
  "ytmdl.deepjyoti30.dev",
  "ytmp3hub.com",
  "yts.lt",
  "zerofs.link"
]);

// ===== UNSAFE BASE NAMES =====

const BASE_UNSAFE_BASE_NAMES = new Set([
  "1377x",
  "kickasstorrents",
  "rargb",
  "thepiratebay",
  "therarbg",
  "torrentlite",
  "animixplay",
  "zoro",
  "soap2day",
  "vegamovies",
  "zlibrary",
  "coolrom",
  "aimhaven",
  "apunkagames",
  "blackboxrepacke",
  "crohasit",
  "crotorrents",
  "descargagame",
  "elamigos",
  "empresstorrents",
  "gamepciso",
  "game3rb",
  "gamefabrique",
  "gamestorrents",
  "gogunlocked",
  "igg",
  "nexus",
  "nosteamgames",
  "oceansofgamess",
  "qoob",
  "steam",
  "wifi4games",
  "allpcworld",
  "appvalley",
  "crackedfully",
  "crackshash",
  "ftuapps",
  "getintopc",
  "haxnode",
  "haxpc",
  "karanpc",
  "kolompc",
  "portable4pc",
  "s0ft4pc",
  "sadeempc",
  "sampledrive",
  "tutubox",
  "vfxdownload",
  "vfxdownloads",
  "yasdl",
  "watchsomuch",
  "yts"
]);

let trustedHosts = new Set(BASE_TRUSTED_HOSTS);
let unsafeBaseNames = new Set(BASE_UNSAFE_BASE_NAMES);

// ===== HELPERS =====

function normalizeHost(hostname) {
  return hostname.toLowerCase().replace(/^www\./, "");
}

function getBaseLabel(hostname) {
  const h = normalizeHost(hostname);
  const parts = h.split(".");
  if (parts.length < 2) return h;
  return parts[parts.length - 2];
}

function classifyDomain(hostname) {
  const normalized = normalizeHost(hostname);
  const base = getBaseLabel(hostname);

  if (trustedHosts.has(hostname) || trustedHosts.has(normalized)) {
    return "safe";
  }
  if (unsafeBaseNames.has(base)) {
    return "unsafe";
  }
  return "unknown";
}

function updateIconForStatus(tabId, status) {
  let path;
  if (status === "safe") {
    path = {
      "16": "icons/icon16-green.png",
      "32": "icons/icon32-green.png",
      "48": "icons/icon48-green.png",
      "128": "icons/icon128-green.png"
    };
  } else if (status === "unsafe") {
    path = {
      "16": "icons/icon16-red.png",
      "32": "icons/icon32-red.png",
      "48": "icons/icon48-red.png",
      "128": "icons/icon128-red.png"
    };
  } else {
    path = {
      "16": "icons/icon16-yellow.png",
      "32": "icons/icon32-yellow.png",
      "48": "icons/icon48-yellow.png",
      "128": "icons/icon128-yellow.png"
    };
  }
  chrome.action.setIcon({ tabId, path });
}

// ===== LOAD CUSTOM LISTS (add-only) =====

function refreshListsFromStorage() {
  trustedHosts = new Set(BASE_TRUSTED_HOSTS);
  unsafeBaseNames = new Set(BASE_UNSAFE_BASE_NAMES);

  chrome.storage.sync.get(["trustedCustom", "unsafeCustom"], (data) => {
    if (Array.isArray(data.trustedCustom)) {
      data.trustedCustom.forEach((host) => {
        if (typeof host === "string" && host.length > 0) {
          trustedHosts.add(host.toLowerCase());
        }
      });
    }

    if (Array.isArray(data.unsafeCustom)) {
      data.unsafeCustom.forEach((base) => {
        if (typeof base === "string" && base.length > 0) {
          unsafeBaseNames.add(base.toLowerCase());
        }
      });
    }
  });
}

refreshListsFromStorage();

chrome.storage.onChanged.addListener((changes, area) => {
  if (area === "sync" && (changes.trustedCustom || changes.unsafeCustom)) {
    refreshListsFromStorage();
  }
});

// ===== TAB EVENTS =====

chrome.tabs.onUpdated.addListener((tabId, changeInfo, tab) => {
  if (changeInfo.status !== "complete" || !tab.url) return;
  try {
    const url = new URL(tab.url);
    const hostname = url.hostname;
    const status = classifyDomain(hostname);
    updateIconForStatus(tabId, status);
  } catch (e) {}
});

chrome.tabs.onActivated.addListener(async (activeInfo) => {
  const tab = await chrome.tabs.get(activeInfo.tabId);
  if (!tab.url) return;
  try {
    const url = new URL(tab.url);
    const hostname = url.hostname;
    const status = classifyDomain(hostname);
    updateIconForStatus(activeInfo.tabId, status);
  } catch (e) {}
});